androidpublisher

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -64,7 +64,7 @@ jobs:
 
       - name: Publish App Bundle
         working-directory: .
-        run: (androidpublisher upload com.bible.studycommentary platforms/android/app/build/outputs/bundle/release/final.aab) || echo 'deploy failure'
+        run: (androidpublisher upload com.bible.studycommentary --aab-file platforms/android/app/build/outputs/bundle/release/final.aab) || echo 'deploy failure'
 
 #      - name: Publish App Bundle
 #        working-directory: .
